### ISSUE TITLE
Personal issue

### ISSUE THREAD

**Issue by IBhopz** [TomGrobbe/vMenu#104]
My Vmenu goes off the screen a littlebit so that i cant see what values or mods i am putting on my car :/
No matter on what server i am on it never works properly it is too much to the right side for me. Can i change that?

**Comment by TomGrobbe** [comment]
@IBhopz What resolution are you using and are you on fullscreen/windowed/windowed borderless?

**Comment by IBhopz** [comment]
I am on windowed borderless and i have tried different resolutions but none have worked

**Comment by IBhopz** [comment]
oh okay i will try again

**Comment by IBhopz** [comment]
changed resolution and restarted fivem its still the same way

**Comment by TomGrobbe** [comment]
> Ok now when i changed it back from 1680 x 1050 to 1920 x 1200 without restarting now i see the whole menu

Sorry for the late response, if I'm not mistaking, that 1680x1050 is a very uncommon resolution, even default GTA doesn't fully support it properly. Because of this, it was never properly implemented in my NativeUI edit. Will have to add/fix support for it in there. For now, there's nothing you can do but wait for it to be fixed, or change the resolution to the one you mentioned that works.

Closing this issue because it'll be added to the issues list for NativeUI instead. Feel free to still reply to this if you have any further questions.

**Comment by IBhopz** [comment]
I mean i was on 1920x1200 and it didnt work properly i changed it to 1680x1050 then restarted and changed back to 1920x1200 and then it worked. Just saying if you first understood it differently :D
