### ISSUE TITLE
Weird rapid fire bug

### ISSUE THREAD

**Issue by matty45** [TomGrobbe/vMenu#119]
On some weapons when you have no reload selected, it causes them to fire rapidly.
One such example is the double action revolver.
The bug also happens if you are firing a weapon out of a car such as the heavy pistol.

**Comment by TomGrobbe** [comment]
> On some weapons when you have no reload selected, it causes them to fire rapidly.
> One such example is the double action revolver.
Sadly, that's how GTA V handles that for (most) MK2 or other dlc weapons. Not much (if anything) that I can change about that.

> The bug also happens if you are firing a weapon out of a car such as the heavy pistol.

Same here, I'm just using GTA V natives. That's how they behave. And since it's not for every weapon, it'd need a shit ton of manual hardcoding and checking every frame if they're firing such hardcoded weapons from a vehicle or similar, and then disable it automatically. Would probably come with even more performance issues and is most likely not worth the 2 clicks to manually disable no reload for normal weapons while in-game.

**Comment by matty45** [comment]
Ah, ok
