### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Blizzard098** [TomGrobbe/vMenu#129]
Greetings,

So somehow vMenu is clipping out of the screen. Would there be any way to fix this? Also, how would someone be able to set the default voice proximity from Global to lets say 10m? Thanks!

https://i.gyazo.com/6fd3362645c1f3c3bfbbce84074909a1.jpg

**Comment by TomGrobbe** [comment]
@Blizzard098 You're either using a custom resolution which is unsupported by GTA V, or you're switching windowing mode (fullscreen/windowed/borderless mode) whenever you join a server, or you're alt-tabbing while in fullscreen mode while joining a server.

As for the default proximity, that's definitely not a bug report and has been answered a million times already: You can't change that, and you will never be able to do that because I'm never going to change that.
