### ISSUE TITLE
Permissions Error

### ISSUE THREAD

**Issue by Blizzard098** [TomGrobbe/vMenu#131]
I seem to be having issues with my permissions:
https://hastebin.com/idusigafec.coffeescript

It works on some people, but not on others. In other words, some of my senior mods are able to use permissions but other people with the same permission are not.

**Comment by TomGrobbe** [comment]
so people in the same group don't have the same permissions? Then that's not a vMenu bug probably but rather a FXServer bug. Because vMenu gets it's permissions info from the server. Either that or you didn't add everyone to the groups using the correct identifiers. Because your permissions.cfg file looks fine.

**Comment by TomGrobbe** [comment]
>Would you suggest I report this bug to CFX Collective? Thanks :D

Only if you have a proper reproduction for this. And I am not able to reproduce this problem myself... You can try, but I'm not sure if they'll be able to reproduce this.

**Comment by Blizzard098** [comment]
Hm alright. Thanks anyways!
