### ISSUE TITLE
the staff only doesn't work

### ISSUE THREAD

**Issue by dragonir44** [TomGrobbe/vMenu#194]
**Describe the bug**
I set permission. cfg correctly but randomly certain person who do not configure in y on access

**To Reproduce**
I don't know how to reproduce it

**Expected behavior**
I need a solution if it possible

**Screenshots**

**vMenu Info**:
- Server ip: la-taverne-rp.tk
- vMenu Version (check the about menu): 3.0.3
- Do you have access to the files? yes
- FXServer artifacts version: i forgot this

**Additional context**
Such as:

- A list of allowed permissions for the player that is having this issue:  theoretically nothing 
- A list of enabled/disabled vMenu features: for who have the admin permission, all

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.
[CitizenFX.log](https://github.com/TomGrobbe/vMenu/files/3228742/CitizenFX.log)

**Comment by dragonir44** [comment]
the bug appeared once again for a user
[CitizenFX.log](https://github.com/TomGrobbe/vMenu/files/3228803/CitizenFX.log)

**Comment by TomGrobbe** [comment]
The first CitizenFX.log file you provided shows that that user was allowed to use vMenu, because they have the vMenu.Staff permission and the staff-only convar is enabled.

So, not sure who that log came from, but they should have had access to it.

Same goes for the second user, vMenu.Staff was allowed so they have access to the menu.

If you did not put these people's identifiers in some config file then you most likely are adding them to the group.admin group through something like essentialmode (which adds them to the group.admin group if they're set as admin iirc). Without a permissions.cfg I won't be able to look into this though.
