### ISSUE TITLE
Multiple Crashes Directly Related to vMenu

### ISSUE THREAD

**Issue by JemmaSinclair** [TomGrobbe/vMenu#299]
**Describe the bug**
While using vMenu, most notably the MP Character Editor, myself and many in my community encounter SetSamplersForPixelShaders and ERR_MEM_EMBEDDEDALLOC_FREE_2.  This is frequent and only occurs while in vMenu.

Most of the members who encounter it use the latest version of NVE.

**To Reproduce**
Spawning multiple different saved MP Peds in a very short span.
Changing clothing very rapidly.
Also randomly happens just when navigating vMenu.

**Screenshots**
![image](https://user-images.githubusercontent.com/61020381/232606955-f5624091-88c0-4178-99ed-1a02877f22b1.png)
The SetSamplersForPixelShaders all happened while the user was navigating vMenu to write down numbers for a EUP Uniform Structure.

**vMenu Info**:
- Server ip: Private Server
- vMenu Version (check the about menu): vMenu v3.5.0
- Do you have access to the files? Yes
- FXServer artifacts version: 6352

**Comment by Drift91** [comment]
> Most of the members who encounter it use the latest version of NVE.

Are you sure it's most and not all? Because I'm fairly certain this is caused by Reshade. My friend's community has been experiencing tons of random crashing too, they mostly all have the latest version of NVE as well. I'm not sure what percentage of the people crashing have NVE though.

While following the installation instructions no one seems to read this text that you're told to add to your `CitizenFX.ini`:
```ini
[Addons]
ReShade5=ID:3cda6465 acknowledged that ReShade 5.x has a bug that will lead to game crashes
```
I can only assume the CFX developers blocked Reshade 5 by default for a reason, and may end up having to block it fully thanks to Razed instructing everyone to bypass the block so he can continue to rake in money on his Patreon after being denied permission to continue using ENBSeries.

I can't 100% for sure nail the blame on Reshade, as I haven't done sufficient testing, but judging by that warning I can only assume that's the most likely cause. Also, I don't have NVE installed, and I'm one of the few people on the server that doesn't get any crashes.

**Comment by Drift91** [comment]
So according to this forum post it might be due to a recent update to FiveM.
https://forum.cfx.re/t/game-crashing-setsamplersforpixelshader/5050983
