### ISSUE TITLE
Menu not showing on 4K

### ISSUE THREAD

**Issue by SolderFish** [TomGrobbe/vMenu#60]
I have a 4k display, and vMenu 1.0.4 is no longer showing up on my display

**Comment by TomGrobbe** [comment]
Thanks for letting me know, I couldn’t easily test this myself so I had to take a gamble on this. I will revert that change first thing tomorrow morning, for now you’ll have to switch back to v1.0.3

**Comment by SolderFish** [comment]
Love the work you are doing! Thank you!

**Comment by TomGrobbe** [comment]
I've tried to replicate it, but so far I've been unable to reproduce this bug. I have to ask this, are you sure it worked fine on v1.0.3 and it broke after (only updating) to v1.0.4? Because I've had some people test it on 1440p and 2650p and it worked fine. I don't get why it'd break on 4k though, and as of this moment, you seem to be the only one who reported this bug :/ so it's really hard to work with the very little information. Mind joining my discord so we can try to figure this out? vespura.com/discord

**Comment by TomGrobbe** [comment]
Solved in #61 
>Fixed menu position on 4k resolutions & fixed a typo in the version checker
