### ISSUE TITLE
Infinite ammo does not work on mk2 weapons

### ISSUE THREAD

**Issue by matty45** [TomGrobbe/vMenu#84]
Infinite ammo does not seem to work on mk2 weapons that have special clips such as full metal jacket rounds. 

Steps to replicate:
1. equip mk2 weapon
2. add special clip component
3. turn on infinite ammo or no reload

**Comment by TomGrobbe** [comment]
this also seems to be due to how the gta v natives work. Unlimited ammo/no-reload is not meant to fill up your ammo all the way, unlimited ammo is just meant to keep it from going down. However, this does not seem to work with the regular natives and needs to be altered to work for mk2 weapons.
added this to the todo list.

**Comment by TomGrobbe** [comment]
#21e5e19 just confirmed fixed it.
