### ISSUE TITLE
Resource Time Warning

### ISSUE THREAD

**Issue by ItsDraconicZ** [TomGrobbe/vMenu#86]
No modifications to the resource causes a Resource Time Warning to all players on a low-medium end system. Replicated on multiple servers, different hardware, all high-end.

**Comment by itismejoey** [comment]
I don't do anything with this resource, but it was mentioned that because it's a huge resource it's bound to have some issues. One of the latest FiveM updates brought what used to be in the background, meaning it's most likely always been happening, to the foreground, where users and admin alike can now see what resource is causing the issue (including possible performance).

**Comment by TomGrobbe** [comment]
> No modifications to the resource causes a Resource Time Warning to all players on a low-medium end system. Replicated on multiple servers, different hardware, all high-end.

What version of vMenu are you using and what settings do you have enabled? (please list all checkboxes you have turned on throughout the menu, and if you noticed disabling some reduce the warnings then please note those options too)

I myself have a pretty decent PC, so it works fine here, but I'm sure on lower end specs it can cause issues. However, some parts of this "lag" is caused by NativeUI, and there is currently no easy way to improve NativeUI's performance, as it's very difficult to debug and figure out what exactly in NativeUI (or vMenu) is causing these warnings to appear for some players, but not for others. vMenu release v1.1.3 provided quite a lot of performance improvements, so if you haven't already, make sure to update to v1.1.3.

Note that the menu does, and always will, cause those warnings on first join, first opening of the menu, and opening _SOME_ submenus for the first time, that's to be expected because it is loading a lot of data for the first time and NativeUI being very poorly optimised, will cause it to lag.

Recent update to FiveM has pushed the 4ms threshold for those messages to appear, to 6ms. Thought that still may cause this warning to appear on low- or med-end PC's, even on most high-end laptops for vMenu. Usually it only shows when using a specific action in the menu, but on less capable machines it can be shown constantly. There is no way for me to fix this completely on _all_ possible hardware combinations and spec levels.
