### ISSUE TITLE
Character Models

### ISSUE THREAD

**Issue by mbergwall2222** [TomGrobbe/vMenu#92]
In Simple Trainer you have the options to edit the character models, like adding tattoos and face paint etc. Is there going to be this option in this menu? Because right now saving these characters causes a plethora of issues that cannot go ignored.

**Comment by TomGrobbe** [comment]
This was mentioned many times in the original thread, yes I'm working on it. In fact, if you read the thread right now, it shows progress on the tattoos, which probably won't be added. But the other features will be added at some point. (reason for the tattoos not being added is because it lacks functionality, which I simply can't make myself because there aren't any natives for them)

**Comment by TomGrobbe** [comment]
also note: feature requests go in the original topic, not on github. Github is only used for bug tracking.
